/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.solutec.ihm;

import fr.solutec.model.User;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author stagiaire
 */
public class Historique extends javax.swing.JFrame {

    /**
     * Creates new form Historique
     */
    private static User u;
    public Historique(User u) {
        this.u = u;
        initComponents();
        this.getRootPane().setDefaultButton(exitHistorique);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayHistorique = new javax.swing.JLabel();
        cbHistorique = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        exitHistorique = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        displayHistorique.setText("Sélectionnez un objectif");

        cbHistorique.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Quotidien", "Hebdomadaire" }));
        cbHistorique.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbHistoriqueItemStateChanged(evt);
            }
        });
        cbHistorique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHistoriqueActionPerformed(evt);
            }
        });
        cbHistorique.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbHistoriquePropertyChange(evt);
            }
        });

        jLabel2.setText("HISTORIQUE");

        exitHistorique.setText("Retour");
        exitHistorique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitHistoriqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitHistorique)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(displayHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addComponent(cbHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addComponent(jLabel2))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(cbHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(displayHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(exitHistorique)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitHistoriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitHistoriqueActionPerformed
        Home fnHome = new Home(u);
        fnHome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitHistoriqueActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
    
    }//GEN-LAST:event_formPropertyChange

    private void cbHistoriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHistoriqueActionPerformed
        
    }//GEN-LAST:event_cbHistoriqueActionPerformed

    private void cbHistoriquePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbHistoriquePropertyChange
    
    }//GEN-LAST:event_cbHistoriquePropertyChange

    private void cbHistoriqueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbHistoriqueItemStateChanged
        String cbR = (String) cbHistorique.getSelectedItem();
        if(cbR.equals("...")){
            displayHistorique.setText("Sélectionnez un objectif");
        }
        if(cbR.equals("Quotidien")){
            displayHistorique.setText("coucou");
        }
        if(cbR.equals("Hebdomadaire")){
            displayHistorique.setText("semaine");
        }
    }//GEN-LAST:event_cbHistoriqueItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historique(u).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbHistorique;
    private javax.swing.JLabel displayHistorique;
    private javax.swing.JButton exitHistorique;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
