/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.solutec.ihm;

import static fr.solutec.dao.ObjectifDao.insertObjectif;
import fr.solutec.model.Objectif;
import fr.solutec.model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Joel B
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private static User u;
    public Home(User u) {
        this.u = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHello = new javax.swing.JLabel();
        homeToEdit = new javax.swing.JButton();
        homeToAnalyse = new javax.swing.JButton();
        homeToHistorique = new javax.swing.JButton();
        deconnexion = new javax.swing.JButton();
        homeToAide = new javax.swing.JButton();
        homeToObjectifs = new javax.swing.JButton();
        newPoids = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        updatePoids = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbHello.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        lbHello.setText("Bonjour");

        homeToEdit.setText("modifier profil");
        homeToEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeToEditActionPerformed(evt);
            }
        });

        homeToAnalyse.setText("Analyse");

        homeToHistorique.setText("Historique");
        homeToHistorique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeToHistoriqueActionPerformed(evt);
            }
        });

        deconnexion.setText("Déconnexion");
        deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexionActionPerformed(evt);
            }
        });

        homeToAide.setText("Aide");

        homeToObjectifs.setText("Objectifs");
        homeToObjectifs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeToObjectifsActionPerformed(evt);
            }
        });

        newPoids.setText("poids");
        newPoids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPoidsActionPerformed(evt);
            }
        });

        jLabel1.setText("kg");

        updatePoids.setText("Ajouter suivi");
        updatePoids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePoidsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 159, Short.MAX_VALUE)
                .addComponent(lbHello)
                .addGap(18, 18, 18)
                .addComponent(homeToEdit)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeToHistorique, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(homeToAnalyse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeToObjectifs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(newPoids, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updatePoids)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(deconnexion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeToAide)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHello)
                    .addComponent(homeToEdit))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPoids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(updatePoids))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(homeToObjectifs)
                .addGap(65, 65, 65)
                .addComponent(homeToHistorique)
                .addGap(57, 57, 57)
                .addComponent(homeToAnalyse)
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deconnexion)
                    .addComponent(homeToAide))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeToHistoriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeToHistoriqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeToHistoriqueActionPerformed

    private void deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionActionPerformed
        Login fnLogin = new Login(u);
        u = null;
        fnLogin.setVisible(true);
        this.setVisible(false);   
    }//GEN-LAST:event_deconnexionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String hello ="Bonjour " + u.getPseudo();
        lbHello.setText(hello);        
    }//GEN-LAST:event_formWindowOpened

    private void homeToEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeToEditActionPerformed
        Profil fnProfil = new Profil(u);
        fnProfil.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_homeToEditActionPerformed

    private void homeToObjectifsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeToObjectifsActionPerformed
        Objectifs fnObjectifs = new Objectifs(u);
        fnObjectifs.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_homeToObjectifsActionPerformed

    private void newPoidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPoidsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPoidsActionPerformed

    private void updatePoidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePoidsActionPerformed
        Objectif update_poids = new Objectif();
        
        update_poids.setPoids(Double.parseDouble(newPoids.getText()));
        update_poids.setObjectifDistance(0);
        update_poids.setObjectifDuree(0);
        update_poids.setObjectifPoids(0);
        try{
            insertObjectif(update_poids);
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_updatePoidsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home(u).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deconnexion;
    private javax.swing.JButton homeToAide;
    private javax.swing.JButton homeToAnalyse;
    private javax.swing.JButton homeToEdit;
    private javax.swing.JButton homeToHistorique;
    private javax.swing.JButton homeToObjectifs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbHello;
    private javax.swing.JTextField newPoids;
    private javax.swing.JButton updatePoids;
    // End of variables declaration//GEN-END:variables
}
